name: Build & Release (Linux/Windows)

on:
  push:
    tags: [ '*' ]

jobs:
  release:
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create ${{ github.ref_name }} -F README.md -t "v${{ github.ref_name }}"

  build:
    needs: release
    permissions: write-all
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            BUILD_NAME: SpeedrunStatsHelper_Windows
            BUILD_ARGS: -F -c main.py
            CMD_EXEC: PyInstaller
            FILE_TYPE: ".exe"
          - os: ubuntu-latest
            BUILD_NAME: SpeedrunStatsHelper_Linux
            BUILD_ARGS: -F -c main.py
            CMD_EXEC: pyinstaller
            FILE_TYPE: ""
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up PyInstaller
      run: |
        python -m pip install --upgrade pip
        python -m pip install PyInstaller
    - name: Build Project for ${{ matrix.os }}
      run: ${{ matrix.CMD_EXEC }} ${{ matrix.BUILD_ARGS }} -n ${{ matrix.BUILD_NAME }} ${{ matrix.CMD_EXTRAS }}
    - name: Upload Release Artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.ref_name }} dist/${{ matrix.BUILD_NAME }}${{ matrix.FILE_TYPE }} times.txt --clobber
